// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChDOXZ42xreyW3YvCfdzwu54tYJN62nSM',
    appId: '1:515199405160:web:85b26a7a24853b4c997fdd',
    messagingSenderId: '515199405160',
    projectId: 'lab8-038',
    authDomain: 'lab8-038.firebaseapp.com',
    storageBucket: 'lab8-038.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Oa4yn0qrbbN8ks_wbwGEWYcj-u7gDbA',
    appId: '1:515199405160:android:709f574c749bf411997fdd',
    messagingSenderId: '515199405160',
    projectId: 'lab8-038',
    storageBucket: 'lab8-038.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo9A5rpaJxU22Q-jz-_mpPyCtJ7vXEL8k',
    appId: '1:515199405160:ios:24c9ad6f0ca0d506997fdd',
    messagingSenderId: '515199405160',
    projectId: 'lab8-038',
    storageBucket: 'lab8-038.firebasestorage.app',
    iosClientId: '515199405160-464pg43m5ud8i166flqjqcdpvna0cenv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8038',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo9A5rpaJxU22Q-jz-_mpPyCtJ7vXEL8k',
    appId: '1:515199405160:ios:24c9ad6f0ca0d506997fdd',
    messagingSenderId: '515199405160',
    projectId: 'lab8-038',
    storageBucket: 'lab8-038.firebasestorage.app',
    iosClientId: '515199405160-464pg43m5ud8i166flqjqcdpvna0cenv.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab8038',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChDOXZ42xreyW3YvCfdzwu54tYJN62nSM',
    appId: '1:515199405160:web:69f6eb8ae6c2504b997fdd',
    messagingSenderId: '515199405160',
    projectId: 'lab8-038',
    authDomain: 'lab8-038.firebaseapp.com',
    storageBucket: 'lab8-038.firebasestorage.app',
  );
}
